controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_yaw_joint
      - left_shoulder_pitch_joint
      - left_shoulder_row_joint
      - left_elbow_yaw_joint
      - left_elbow_row_joint
      - left_wrist_pitch_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_yaw_joint
      - right_shoulder_pitch_joint
      - right_shoulder_row_joint
      - right_elbow_yaw_joint
      - right_elbow_row_joint
      - right_wrist_pitch_joint