philos:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - left_shoulder_yaw_joint
      - left_shoulder_pitch_joint
      - left_shoulder_row_joint
      - left_elbow_yaw_joint
      - left_elbow_row_joint
      - left_wrist_pitch_joint
      - neck_row_joint
      - neck_yaw_joint
      - neck_pitch_joint
      - right_shoulder_yaw_joint
      - right_shoulder_pitch_joint
      - right_shoulder_row_joint
      - right_elbow_yaw_joint
      - right_elbow_row_joint
      - right_wrist_pitch_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  left_arm_controller:
    type: position_controllers/JointPositionController
    joints:
      - left_shoulder_yaw_joint
      - left_shoulder_pitch_joint
      - left_shoulder_row_joint
      - left_elbow_yaw_joint
      - left_elbow_row_joint
      - left_wrist_pitch_joint
    gains:
      left_shoulder_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_shoulder_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_shoulder_row_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_elbow_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_elbow_row_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_wrist_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  right_arm_controller:
    type: position_controllers/JointPositionController
    joints:
      - right_shoulder_yaw_joint
      - right_shoulder_pitch_joint
      - right_shoulder_row_joint
      - right_elbow_yaw_joint
      - right_elbow_row_joint
      - right_wrist_pitch_joint
    gains:
      right_shoulder_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_shoulder_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_shoulder_row_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_elbow_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_elbow_row_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_wrist_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1