# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
neck_row_joint_controller:
  type: position_controllers/JointPositionController
  joint: neck_row_joint
  pid: {p: 2000.0, i: 100, d: 500.0}

neck_yaw_joint_controller:
  type: position_controllers/JointPositionController
  joint: neck_yaw_joint
  pid: {p: 5000.0, i: 10000, d: 2000.0}

neck_pitch_joint_controller:
  type: position_controllers/JointPositionController
  joint: neck_pitch_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

left_shoulder_row_joint_controller:
  type: position_controllers/JointPositionController
  joint: left_shoulder_row_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

left_shoulder_pitch_joint_controller:
  type: position_controllers/JointPositionController
  joint: left_shoulder_pitch_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

left_shoulder_yaw_joint_controller:
  type: position_controllers/JointPositionController
  joint: left_shoulder_yaw_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

left_elbow_yaw_joint_controller:
  type: position_controllers/JointPositionController
  joint: left_elbow_yaw_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

left_elbow_row_joint_controller:
  type: position_controllers/JointPositionController
  joint: left_elbow_row_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

left_wrist_pitch_joint_controller:
  type: position_controllers/JointPositionController
  joint: left_wrist_pitch_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

right_shoulder_row_joint_controller:
  type: position_controllers/JointPositionController
  joint: right_shoulder_row_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

right_shoulder_pitch_joint_controller:
  type: position_controllers/JointPositionController
  joint: right_shoulder_pitch_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

right_shoulder_yaw_joint_controller:
  type: position_controllers/JointPositionController
  joint: right_shoulder_yaw_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

right_elbow_yaw_joint_controller:
  type: position_controllers/JointPositionController
  joint: right_elbow_yaw_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

right_elbow_row_joint_controller:
  type: position_controllers/JointPositionController
  joint: right_elbow_row_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}

right_wrist_pitch_joint_controller:
  type: position_controllers/JointPositionController
  joint: right_wrist_pitch_joint
  pid: {p: 2000.0, i: 50, d: 1000.0}